# Shallow Net in KERAS

Build a shallow neural network to classify MNIST data

#### set seed reprodicibility

In [2]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [26]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers

#### Load Data

In [27]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [28]:
X_train.shape

(60000, 28, 28)

In [29]:
y_train.shape

(60000,)

In [30]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [31]:
X_train[5]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  13,  25, 100, 122,   7,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [32]:
X_test.shape

(10000, 28, 28)

In [33]:
y_test.shape

(10000,)

#### Preprocess Data

In [34]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [35]:
X_train /= 255
X_test /= 255

In [36]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [37]:
y_train[0]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

#### Design neural network architecture 

In [38]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [39]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


#### Configure Model 

In [42]:
model.compile(loss='mean_squared_error', optimizer=optimizers.SGD(lr=0.01), metrics=['accuracy'])

#### Train

In [43]:
model.fit(X_train, y_train, batch_size=128, epochs=200, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s - loss: 0.0917 - acc: 0.1290 - val_loss: 0.0913 - val_acc: 0.1444
Epoch 2/200
60000/60000 [==============================] - 1s - loss: 0.0910 - acc: 0.1461 - val_loss: 0.0907 - val_acc: 0.1667
Epoch 3/200
60000/60000 [==============================] - 1s - loss: 0.0904 - acc: 0.1680 - val_loss: 0.0902 - val_acc: 0.1857
Epoch 4/200
60000/60000 [==============================] - 1s - loss: 0.0899 - acc: 0.1875 - val_loss: 0.0897 - val_acc: 0.1998
Epoch 5/200
60000/60000 [==============================] - 1s - loss: 0.0895 - acc: 0.1998 - val_loss: 0.0893 - val_acc: 0.2092
Epoch 6/200
60000/60000 [==============================] - 1s - loss: 0.0891 - acc: 0.2073 - val_loss: 0.0889 - val_acc: 0.2116
Epoch 7/200
60000/60000 [==============================] - 1s - loss: 0.0887 - acc: 0.2119 - val_loss: 0.0885 - val_acc: 0.2132
Epoch 8/200
60000/60000 [=============================

60000/60000 [==============================] - 1s - loss: 0.0628 - acc: 0.5864 - val_loss: 0.0622 - val_acc: 0.5912
Epoch 65/200
60000/60000 [==============================] - 1s - loss: 0.0623 - acc: 0.5907 - val_loss: 0.0618 - val_acc: 0.5964
Epoch 66/200
60000/60000 [==============================] - 1s - loss: 0.0619 - acc: 0.5945 - val_loss: 0.0613 - val_acc: 0.6019
Epoch 67/200
60000/60000 [==============================] - 1s - loss: 0.0615 - acc: 0.5979 - val_loss: 0.0609 - val_acc: 0.6053
Epoch 68/200
60000/60000 [==============================] - 1s - loss: 0.0610 - acc: 0.6015 - val_loss: 0.0605 - val_acc: 0.6083
Epoch 69/200
60000/60000 [==============================] - 1s - loss: 0.0606 - acc: 0.6057 - val_loss: 0.0600 - val_acc: 0.6117
Epoch 70/200
60000/60000 [==============================] - 1s - loss: 0.0602 - acc: 0.6089 - val_loss: 0.0596 - val_acc: 0.6150
Epoch 71/200
60000/60000 [==============================] - 1s - loss: 0.0598 - acc: 0.6123 - val_loss: 0.0592

60000/60000 [==============================] - 1s - loss: 0.0422 - acc: 0.7504 - val_loss: 0.0415 - val_acc: 0.7598
Epoch 128/200
60000/60000 [==============================] - 1s - loss: 0.0420 - acc: 0.7522 - val_loss: 0.0412 - val_acc: 0.7621
Epoch 129/200
60000/60000 [==============================] - 1s - loss: 0.0417 - acc: 0.7548 - val_loss: 0.0410 - val_acc: 0.7639
Epoch 130/200
60000/60000 [==============================] - 1s - loss: 0.0415 - acc: 0.7570 - val_loss: 0.0408 - val_acc: 0.7655
Epoch 131/200
60000/60000 [==============================] - 1s - loss: 0.0413 - acc: 0.7596 - val_loss: 0.0405 - val_acc: 0.7672
Epoch 132/200
60000/60000 [==============================] - 1s - loss: 0.0410 - acc: 0.7612 - val_loss: 0.0403 - val_acc: 0.7692
Epoch 133/200
60000/60000 [==============================] - 1s - loss: 0.0408 - acc: 0.7633 - val_loss: 0.0401 - val_acc: 0.7705
Epoch 134/200
60000/60000 [==============================] - 1s - loss: 0.0406 - acc: 0.7651 - val_loss:

60000/60000 [==============================] - 1s - loss: 0.0309 - acc: 0.8453 - val_loss: 0.0300 - val_acc: 0.8568
Epoch 191/200
60000/60000 [==============================] - 1s - loss: 0.0308 - acc: 0.8461 - val_loss: 0.0299 - val_acc: 0.8575
Epoch 192/200
60000/60000 [==============================] - 1s - loss: 0.0306 - acc: 0.8468 - val_loss: 0.0297 - val_acc: 0.8584
Epoch 193/200
60000/60000 [==============================] - 1s - loss: 0.0305 - acc: 0.8475 - val_loss: 0.0296 - val_acc: 0.8589
Epoch 194/200
60000/60000 [==============================] - 1s - loss: 0.0304 - acc: 0.8480 - val_loss: 0.0295 - val_acc: 0.8600
Epoch 195/200
60000/60000 [==============================] - 1s - loss: 0.0302 - acc: 0.8487 - val_loss: 0.0293 - val_acc: 0.8605
Epoch 196/200
60000/60000 [==============================] - 1s - loss: 0.0301 - acc: 0.8496 - val_loss: 0.0292 - val_acc: 0.8610
Epoch 197/200
60000/60000 [==============================] - 1s - loss: 0.0300 - acc: 0.8500 - val_loss: